/**
 * Centralized error codes for API responses.
 * Client translates these codes using i18n.
 */
export const ErrorCodes = {
  // Auth errors
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_CHECK_EMAIL: 'AUTH_CHECK_EMAIL',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_IDEA_MIN_LENGTH: 'VALIDATION_IDEA_MIN_LENGTH',
  VALIDATION_IDEA_MAX_LENGTH: 'VALIDATION_IDEA_MAX_LENGTH',
  VALIDATION_INVALID_TEMPLATE: 'VALIDATION_INVALID_TEMPLATE',
  VALIDATION_INVALID_VERSION: 'VALIDATION_INVALID_VERSION',
  VALIDATION_INVALID_WORKSPACE_ID: 'VALIDATION_INVALID_WORKSPACE_ID',
  VALIDATION_INVALID_PRD_ID: 'VALIDATION_INVALID_PRD_ID',
  VALIDATION_FEEDBACK_MIN_LENGTH: 'VALIDATION_FEEDBACK_MIN_LENGTH',
  VALIDATION_FEEDBACK_MAX_LENGTH: 'VALIDATION_FEEDBACK_MAX_LENGTH',
  VALIDATION_SECTIONS_MIN: 'VALIDATION_SECTIONS_MIN',
  VALIDATION_SECTIONS_MAX: 'VALIDATION_SECTIONS_MAX',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_PASSWORD_MIN_LENGTH: 'VALIDATION_PASSWORD_MIN_LENGTH',
  VALIDATION_PASSWORD_MAX_LENGTH: 'VALIDATION_PASSWORD_MAX_LENGTH',
  VALIDATION_NAME_MIN_LENGTH: 'VALIDATION_NAME_MIN_LENGTH',
  VALIDATION_NAME_MAX_LENGTH: 'VALIDATION_NAME_MAX_LENGTH',
  VALIDATION_INVALID_USER_ID: 'VALIDATION_INVALID_USER_ID',

  // Credit errors
  CREDITS_INSUFFICIENT: 'CREDITS_INSUFFICIENT',
  CREDITS_REFUND_FAILED: 'CREDITS_REFUND_FAILED',
  WORKSPACE_CREDITS_INSUFFICIENT: 'WORKSPACE_CREDITS_INSUFFICIENT',

  // Package/Plan errors
  PACKAGE_INVALID: 'PACKAGE_INVALID',
  PACKAGE_NOT_CONFIGURED: 'PACKAGE_NOT_CONFIGURED',
  PLAN_INVALID: 'PLAN_INVALID',
  PLAN_NOT_CONFIGURED: 'PLAN_NOT_CONFIGURED',

  // Subscription errors
  SUBSCRIPTION_ALREADY_ACTIVE: 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_FETCH_FAILED: 'SUBSCRIPTION_FETCH_FAILED',

  // Payment errors
  PAYMENT_SYSTEM_ERROR: 'PAYMENT_SYSTEM_ERROR',
  PAYMENT_CHECKOUT_FAILED: 'PAYMENT_CHECKOUT_FAILED',
  PAYMENT_PROCESSING_ERROR: 'PAYMENT_PROCESSING_ERROR',

  // PRD errors
  PRD_NOT_FOUND: 'PRD_NOT_FOUND',
  PRD_CONTENT_UNREADABLE: 'PRD_CONTENT_UNREADABLE',
  PRD_SAVE_FAILED: 'PRD_SAVE_FAILED',
  PRD_LIST_FAILED: 'PRD_LIST_FAILED',
  PRD_GENERATION_FAILED: 'PRD_GENERATION_FAILED',

  // Workspace errors
  WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',

  // Rate limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // General errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
