/**
 * PRD PDF Document Component
 *
 * @react-pdf/renderer Document for generating PDF.
 * NOTE: This component must NOT be imported in server components.
 * Always use dynamic import with ssr: false.
 */

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';

// Styles for A4 page
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    fontWeight: 'bold',
    color: '#111827',
  },
  content: {
    fontSize: 12,
    lineHeight: 1.6,
    color: '#374151',
    whiteSpace: 'pre-wrap',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    marginBottom: 8,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  paragraph: {
    fontSize: 12,
    lineHeight: 1.6,
    color: '#374151',
    marginBottom: 8,
  },
  metadata: {
    fontSize: 10,
    color: '#6b7280',
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 10,
    color: '#9ca3af',
    textAlign: 'center',
  },
});

/**
 * Removes Markdown formatting tags for plain text display
 */
function stripMarkdown(markdown: string): string {
  return markdown
    // Remove headers (# ## ### etc)
    .replace(/^#{1,6}\s+/gm, '')
    // Remove bold/italic
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/_([^_]+)_/g, '$1')
    // Remove inline code
    .replace(/`([^`]+)`/g, '$1')
    // Remove code blocks
    .replace(/```[\s\S]*?```/g, '')
    // Remove links, keep text
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    // Remove images
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, '$1')
    // Remove horizontal rules
    .replace(/^---+$/gm, '')
    .replace(/^\*\*\*+$/gm, '')
    // Remove list markers
    .replace(/^\s*[-*+]\s+/gm, '- ')
    .replace(/^\s*\d+\.\s+/gm, '')
    // Clean up extra whitespace
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

interface PrdDocumentProps {
  prd: {
    id: string;
    title: string;
    content?: {
      markdown?: string;
      [key: string]: unknown;
    };
  };
}

export function PrdDocument({ prd }: PrdDocumentProps) {
  const markdown = prd.content?.markdown ?? '';
  const plainText = stripMarkdown(markdown);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Title */}
        <Text style={styles.title}>{prd.title || 'Untitled PRD'}</Text>

        {/* Metadata */}
        <View style={styles.metadata}>
          <Text>Generated by IdeaToPRD</Text>
        </View>

        {/* Content */}
        <View style={styles.section}>
          <Text style={styles.content}>{plainText}</Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          IdeaToPRD - Transform your ideas into actionable product documents
        </Text>
      </Page>
    </Document>
  );
}
